version: "3.9"

services:
  api:
    container_name: node-docker-container
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - backend
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres:14.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      # - ./postgresdata:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
    networks:
      - backend
